sudo: required
dist: trusty
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: Tddv/PyRCjTrektnonH1ZniR3Sf3xlz547LrHJUKeJ0pMcFNJTYzxXJfvF+ozocVOok4rwW9xPBscHEZLZM8UnAwRPiGQ2gECc8b35AjjBQ8zFuWLsKBkmpHV9Sd3PHRb8ejvcX4nrdnygdzLL5pZHM8vM/O8M57QVowHTn2ZL+J2bFT0W264ffSet62FzKz+8LaCsPs4ix5eUhVT30vbJl1NGTju5jzz8azmvALdfuTzdIy5HKu8Lu20pJvLi7/J21YtHoSjCmf1hq+/Kf7IH5/GvF4YkT1927Sn0I0kG3Xrb8Xrbuhq0INJ11VtwQlUjBZbZgQ4yykOVotPybDAGshU3QKTzD6bWBpLDxuv/gYgrUB0H6Pk899Al/wq7M2oFxWrjtmtKN/aFJ3DPiduPVP1O6wAdDskxLTIT0zB0mQq+S/89MXnxJoCSTKdkGx6Ol7zdi6zBw5Eg5CLE1xZ3pICA30kfb26QVGxHDduWRg/TgsAtn1FKkMQmni9JOjzVmO9Ir8w5a6bdSM/qHXKV3D2rmmEBQPoidQOM4FVYH7RlcKPEaV5tS97gHabqR1flh8N0IDTxvNZNL8me0qXyjy9JpiDKt+r3BefU7hRbYeD431MFGlVT7FOZ1CpKXWJOubZv/ZgwVbZ0gvWwhQftj2D5bEFYZ3iBhItPclotU=
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml'
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_NEO4J_HOST=127.0.0.1
  - CEDAR_NEO4J_USER_NAME=neo4j
  - CEDAR_NEO4J_USER_PASSWORD=password
  - CEDAR_NEO4J_BOLT_PORT=7687
  - CEDAR_MONGO_HOST=127.0.0.1
  - CEDAR_MONGO_PORT=27017
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_ELASTICSEARCH_HOST=127.0.0.1
  - CEDAR_ELASTICSEARCH_TRANSPORT_PORT=9300
  - CEDAR_REDIS_PERSISTENT_HOST=127.0.0.1
  - CEDAR_REDIS_PERSISTENT_PORT=6379
  - CEDAR_INTERNALS_HTTP_PORT=9014
  - CEDAR_INTERNALS_ADMIN_PORT=9114
  - CEDAR_INTERNALS_STOP_PORT=9214
  - CEDAR_LOG_MYSQL_HOST=127.0.0.1
  - CEDAR_LOG_MYSQL_PORT=3306
  - CEDAR_LOG_MYSQL_DB=cedar_log
  - CEDAR_LOG_MYSQL_USER=cedar_log_user
  - CEDAR_LOG_MYSQL_PASSWORD=cedar_log_password
  - secure: ef0PICN/55OJ0cP86Qp0Lu2DTCypPkyswRdXTuYUVLD1zxB+m1IqdNJYdMmCKyIi3lnTvNErVQasEu61R6htn+FkWTe+DZBYLYXVSBZl7B+pVd43oQBdQBsn6dc9Y9zHOPrCsAc4auHHgOmpGL894v1VsauYYFuU1/Xso5BhHgaWoyQrWBKeeH3z1JMfFeyaPfA4dF1zXljfd+ydSZV6+b7izyUjLH/HUI7D3kgO0IqZbexPK4Sj0dF+YoGnmgCaUOQvQaNJhLu0IHYy0tlCSWPuRktm5W931gQw52GusYCadczq46QXWBeXLlx5kyreT5eFDW21wgmIsNCid36nde3IofoWXGl713agtc+MQr91qj6rdTWGMqF9a7sdAeqjdV3a9oXhyOM2so8wBjC6WdAMYMTWBIKH8yuq0Vf4ZiqVlzb2djPMFZFaMYZyV5zRdTSHaXaqVfoaJKOh0+fzScvhZFvgppohcMDrvqSDKBOraDTemSo0MNcB3vycEgxQq7PaOlbxl4ihO17zuZ1ZMdXbp5ezHW+0xDgvmv4gaLTv6IY3NHf/eNtdDVDelBPZi5Y9yeqQn67wSSYpdvJsYHqhi6SMmrDviLzOWckh6GvvU5oJoFg3q5mm08WFCcBDXtWdP/XqoQE9ia4wIq/sdX9mVi8G4HBC9zjT49ZCEqU=
  - secure: e923uAJHKooVDJbbxbfxTsDk9+F3+C8dN5RzeehGrgZqsXBZZIjLitMu7EWfe90VmxEp6sdoLLHnajvVbQW5kruF5Cj8kN2jPziVktB4lt7e/wv6D3GHNAKAqfRYJEazuAaZVGl3dFtwG8bOb2mhjzG8BnOP9WFFV/fQCDTzXWL8v+wBtCh7D/mGj6kQEPH1aBrYB9irIapk28C+UK1PqA2ojTe3sHkMcNL8kNyfbCT+3SV9/mYDbx1yqHAcOnSYy3EYy//0L5d5Eot3TjqB7NqRdMrhXkjKJTwx7NUJdoR3bMkZ3L9ilBs9TgkzUrW7JOi9+0sbHXJ5+mq0u4Z5rPV+RfC/yXaEewOQ28PrPQhw1v/eWDJVtD1n8ve8hFmeKhgRUOnoVlb2BONZ/rstIabtjhTcrg5jwUkJzfTzLPlK5dS9vjc2L1qVKOXLCje/rf7mmHreFys0WWeU5PWGjkCqT7g4Aa2e4/pdWcIkSQmvaSYyOY2k6oCliN9WzDc7vT8qdwEPtnF64r2rFVPZ64wyeJ/oaNKCrMzDWIqRBL2lLU8ipxieQvf1gnUeJ/Qqnwyo78H2NDP6zunANZ2bNJb7SCiXmHLAmsU0XmaIlWRX4OVJdrhBtnALos065CCnu3Qh8t1SWtUVG5c9sUzU4Oe+W9Avq8N8BwGg2nR+utg=
